@startuml milestonesUseCase
!theme cerulean-outline
skinparam defaultFontName Arial
actor Client
actor Freelancer
participant "Message Module" as MM
participant "Contract Module" as CM
participant PayPal
participant Firestore as FB

title Milestones Use Case

Client -> MM : Go to chat with Freelancer
MM -> MM : Load chat history and \ninterface to interact with \nFreelancer and contract
Client -> CM : Click "View Contract"
CM -> CM : Load contract details
group Contract Module interaction for Client
  alt Milestone NOT funded
    Client -> CM : Click "Fund Milestone"
    CM -> CM : Show Payment Dialog
    CM -> PayPal: Send Payment request
    PayPal -> FB : Payment Approved
    FB --> FB : Milestone status \nupdated to funded
    FB -> MM : Notify Freelancer    
  end
  alt Milestone submitted or funded
    Client -> CM : Click "Release funds"
    CM -> FB : Send request
    FB --> FB : Funds released \nto Freelancer
    FB -> MM : Notify Freelancer    
    Client -> CM : Click "Request refund"
    CM -> FB : Send request
    FB --> FB : Milestone status \nupdated to \nrefund-requested
  end
end

Freelancer -> MM : Go to chat with Client
MM -> MM : Load chat history and \ninterface to interact with \nClient and contract
Freelancer -> CM : Click "View Contract"
CM -> CM : Load contract details
group Contract Module interaction for Freelancer
  alt Milestone funded
    Freelancer -> CM : Click "Submit Milestone"
    CM -> FB : Send request
    FB --> FB : Milestone status \nupdated \nto submitted
    FB -> MM : Notify Client
  end
  alt Milestone refund-requested
    Freelancer -> CM : Click "Deliver again"
    CM -> FB : Send request
    FB --> FB : Milestone status \nupdated \nto submitted
    FB -> MM : Notify Client
  end
end

@enduml
