@startuml messaging

!theme cerulean-outline
skinparam defaultFontName Arial
title Messaging Use Case on FreeEcu

actor "User 1" as U1
actor "User 2" as U2
participant "FreEcu Website" as WEB

U1 -> WEB: Navigate to /find-people page
WEB -> WEB: Display search interface
U1 -> WEB: Perform search

alt User Found
    U1 -> WEB: Click on 'Send Message' to a user
    WEB -> WEB: Check if chat with User 2 exists
    
    alt Chat Exists
        WEB -> WEB: Display "Chat already exists"
        U1 -> WEB: Click on "Go to chat"
        WEB -> U1: Display existing chat session
    else No Chat Exists
        WEB -> WEB: Display new message box
        U1 -> WEB: Fill out message box with initial message
        U1 -> WEB: Click 'Send'
        WEB -> WEB: Create new chat session at /messages/chatID
        WEB -> U1: Display new /messages/chatID page
    end
    
else User Not Found
    WEB -> U1: Display 'No User Found' message
end

U2 -> WEB: Navigate to /messages/chatID
WEB -> WEB: Display message request or existing chat
alt New Chat Request
    U2 -> WEB: Click on 'Accept Request'
    WEB -> U2: Open new chat session
else Existing Chat
    WEB -> U2: Continue in existing chat session
end

@enduml
