@startuml registrationUseCase

!theme cerulean-outline
skinparam defaultFontName Arial
skinparam backgroundColor white

title User Registration Use Case

actor User as U
participant "FreEcu Website" as WEB

U -> WEB: Navigate to website's landing page
WEB -> WEB: Display landing page
U -> WEB: Click on Sign Up button
WEB -> WEB: Display Sign Up form
U -> WEB: Fill out Sign Up form
WEB -> WEB: Validate form input
WEB -> U: Send verification email\nwith confirmation link
WEB -> WEB: Display /complete-signup page
U -> U: Check email inbox
U -> WEB: Click on confirmation link
WEB -> WEB: Wait for email confirmation
U -> WEB: Complete account setup
WEB -> WEB: Update user account\nand profile
WEB -> U: Display confirmation message\nand account dashboard
@enduml
